### ISSUE TITLE
make test

### ISSUE THREAD

**Issue by Huelse** [K-miran/HEMat#3]
When I make the test, it showed a lot of reference errors.
![e](https://i.loli.net/2020/02/13/wOtLzHNGadlhSjX.jpg)
How to sovle it?
By the way, Can this project rewrite in the latest HEAAN(2.1)?
Thanks in advance.

**Comment by MasterSkepticista** [comment]
Can you also please link the fix before closing issue?

**Comment by Huelse** [comment]
@MasterSkepticista 
In fact, I haven't received any answer.
But I rebuild it in the latest HEANN lib with refer to this lib and the paper.

**Comment by by202** [comment]
I have same issue here, could you let us know how to solve it?

**Comment by EchizenG** [comment]
The solution is #7

**Comment by mokatto** [comment]
> The solution is #7

Why does it remain undefined after I have modified the Makefile? I re-executed the make new command, can you help me?
